---

- name: "Playbook to test NAPALM-Ansible"
  hosts: all
  connection: network_cli

  tasks:
    - name: "Retrieve device facts from hosts via NAPALM"
      napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        optional_args: "{{ opt_args }}"
        filter: ["vlans"]
      register: napalm_result

    - name: "Print result"
      ansible.builtin.debug:
        msg: "{{ napalm_result.ansible_facts.napalm_vlans }}"
