---

- name: "Playbook to validate devices"
  hosts: all
  connection: network_cli

  tasks:
    - name: "Task 1 - NAPALM validate"
      napalm_validate:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        optional_args: "{{ opt_args }}"
        validation_file: "{{ inventory_hostname }}-ip.yml"
      register: result
      ignore_errors: yes

    - name: "Print result"
      ansible.builtin.debug:
        msg: "{{ result }}"
