---

- name: "Play 1 - Configuring devices using RESTCONF"
  hosts: 10.0.0.18
  connection: local

  tasks:
    - name: "Task 1 - Configure OSPF"
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}/restconf/data/native/router"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: PUT
        headers:
          Accept:
            application/yang-data+json,
            application/yang-data.errors+json
          Content-Type: 'application/yang-data+json'
        body_format: json
        body: "{{ ospf_config }}"
        validate_certs: false
        status_code:
          - 200
          - 204

    - name: "Task 2 - Configure ACL"
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}/restconf/data/native/ip/access-list"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: PUT
        # method: PATCH - use to update instead of replace
        headers:
          Accept:
            application/yang-data+json,
            application/yang-data.errors+json
          Content-Type: 'application/yang-data+json'
        body_format: json
        body: "{{ acl_config }}"
        validate_certs: false
        status_code:
          - 200
          - 204
