---

- name: "VLAN interface configs via Jinja"
  hosts: cisco
  connection: network_cli

  tasks:
    - name: "Configure Cisco interface VLAN config"
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.interface }}"
            mode: access
            access:
              vlan: "{{ item.vlan }}"
        state: merged
      register: ios_output
      loop: "{{ vlans.interfaces }}"
      when: item.mode == "access"

    - name: "Print Cisco config"
      ansible.builtin.debug:
        msg: "{{ ios_output }}"
