---

- name: "VLAN configs via Jinja"
  hosts: cisco
  connection: network_cli

  tasks:
    - name: "Push Cisco VLAN config"
      cisco.ios.ios_config:
        src: "{{ ansible_network_os }}-vlan.j2"
        # match: "none"
      register: cisco_output

    - name: "Print Cisco VLAN config"
      ansible.builtin.debug:
        msg: "{{ cisco_output }}"
