---

- name: "Conditional test"
  hosts: usa
  gather_facts: true
  gather_subset: all
  connection: network_cli

  tasks:
    - name: "Task 1"
      debug: 
        # msg: "{{ item['key'] }} has a value of {{ item['value']['ipv4'][0]['address'] }}"
        msg: "{{ item.key }} has a value of {{ item.value.ipv4.0.address }}"
      loop: "{{ ansible_net_interfaces | dict2items }}"
      # when: item['value']['lineprotocol'] == "up"
      # when: item['value']['ipv4'] != []
      when: item.value.ipv4 != []