---
# tasks file for eigrp_role

- name: "Task 1 - {{ task_one_name }}"
  cisco.ios.ios_config:
    src: "{{ eigrp_template }}"
  register: eigrp_result

- name: "Task 2 - {{ task_two_name }}"
  ansible.builtin.debug:
    msg: "{{ eigrp_result.commands }}"

- name: "Task 3 - {{ task_three_name }}"
  cisco.ios.ios_command:
    commands:
      - "show run | section eigrp"
  register: eigrp_show_output

- name: "Task 4 - {{ task_four_name }}"
  ansible.builtin.debug:
    msg: "{{ eigrp_show_output.stdout_lines }}"
