---

- name: "Simple gather facts with all subset on usa hosts"
  hosts: usa
  gather_facts: true
  gather_subset:
    - all
  connection: network_cli

  tasks:
    - name: "Gathering facts"
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
