---

- name: "NTP Config Playbook"
  hosts: usa
  gather_facts: false
  connection: network_cli

  tasks:
  - name: "Loop through and configure NTP on routers"
    vars:
      myntpservers:
        - "1.1.1.1"
        - "2.2.2.2"
        - "3.3.3.3"
        - "4.4.4.4"
    cisco.ios.ios_ntp_global:
      config:
        peers:
          - peer: "{{ item }}"
            version: 2
    loop: "{{ myntpservers }}"
