---

- name: FIRST PLAYBOOK
  hosts: cisco
  gather_facts: false
  connection: network_cli

  tasks:
    - name: OSPF CONFIGURATION
      cisco.ios.ios_config:
        lines:
          - router-id 33.44.88.22
        parents:
          - router ospf 19
      register: my_output

    - name: SAVE CONFIGURATION
      cisco.ios.ios_command:
        commands:
          - command: 'write memory'
            prompt: 'Overwrite the previous NVRAM configuration?[confirm]'
            answer: 'yes'
    - name: DEBUG
      debug: var=my_output
