---

- name: "Register playbook"
  hosts: "10.0.0.10"
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Push config"
      cisco.ios.ios_config:
        src: ntp.j2
      register: ntp_results

    - name: "Print results"
      ansible.builtin.debug:
        msg: "{{ ntp_results }}"
