---

- name: "BGP Playbook"
  hosts: all
  connection: network_cli

  tasks:
    - name: "Push Cisco BGP config"
      cisco.ios.ios_config:
        src: "{{ ansible_network_os }}-bgp.j2"
      register: cisco_output
      when: "ansible_network_os == 'cisco.ios.ios'"

    - name: "Print Cisco BGP config"
      ansible.builtin.debug:
        msg: "{{ cisco_output }}"
      when: "ansible_network_os == 'cisco.ios.ios'"

    - name: "Push VyOS BGP config"
      vyos.vyos.vyos_config:
        src: "{{ ansible_network_os }}-bgp.j2"
      register: vyos_output
      when: "ansible_network_os == 'vyos.vyos.vyos'"

    - name: "Print VyOS BGP config"
      ansible.builtin.debug:
        msg: "{{ vyos_output }}"
      when: "ansible_network_os == 'vyos.vyos.vyos'"
